plugins {
    id "fabric-loom" version "1.10.5"
    id "maven-publish"
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    exclusiveContent {
        forRepository {
            maven { url = "https://api.modrinth.com/maven" }
        }
        filter { includeGroup "maven.modrinth" }
    }
    maven { url = "https://maven.shedaniel.me/" }
    maven { url = "https://maven.terraformersmc.com/releases/" }
    maven { url = "https://mvn.devos.one/releases" }
    ivy {
        name = "createUfoPortRelease"
        url = "https://github.com/vlad250906/Create-UfoPort/releases/download/release/1.21/dd"
        patternLayout { artifact "create-fabric-ufoport-0.9.3-d+mc1.21-1.21.1.[ext]" }
        metadataSources { artifact() }
        content { includeGroup "create.ufoport.direct" }
    }
    mavenCentral()
}

def ufoPortCoordinate = "create.ufoport.direct:create-ufoport:${project.create_version}"
def ufoPortBundle = configurations.detachedConfiguration(dependencies.create(ufoPortCoordinate))
def ufoPortCompileDirectory = new File(gradle.gradleUserHomeDir, "caches/create-ufoport-compile/${project.create_version}")
project.sync { spec ->
    spec.from(zipTree(ufoPortBundle.singleFile)) {
        include "META-INF/jars/*.jar"
        eachFile { path = name }
        includeEmptyDirs = false
    }
    spec.into ufoPortCompileDirectory
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
    modImplementation ufoPortCoordinate
    modCompileOnly fileTree(ufoPortCompileDirectory) { include "*.jar" }
    modImplementation "me.shedaniel.cloth:cloth-config-fabric:${project.cloth_config_version}"
    modCompileOnly "maven.modrinth:modmenu:${project.modmenu_version}"
}

processResources {
    inputs.property "version", project.version
    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release = 21
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}
